name: logcat-colorize
base: core18
version: "0.10.1"
summary: logcat-colorize
confinement: strict
grade: stable
description: |
  logcat-colorize is a software that parses Android logcat output and
  prints it to stdout with improved formatting. Colors are added to the
  output to make it more clear. You'll still be able to add filters using
  the adb command.

apps:
  logcat-colorize:
    command: usr/bin/logcat-colorize

parts:
  logcat-colorize:
    plugin: make
    source-type: git
    source-tag: v0.10.1
    source: https://github.com/carlonluca/logcat-colorize.git
    build-packages:
      - g++
      - make
      - libboost-regex1.65-dev
      - libboost-program-options1.65-dev
    stage-packages:
      - libboost-regex1.65.1
      - libboost-program-options1.65.1
